module.exports = {
  initializeApp: jest.fn(() => ({})),
  getApps: jest.fn(() => []),
  getApp: jest.fn(() => ({})),
  initializeAuth: jest.fn(() => ({
    currentUser: { uid: 'test-uuid', email: 'test@example.com' },
    signOut: jest.fn(),
  })),
  getReactNativePersistence: jest.fn(),
  initializeFirestore: jest.fn(() => ({})),
  persistentLocalCache: jest.fn(),
  persistentMultipleTabManager: jest.fn(),
  collection: jest.fn(),
  doc: jest.fn(),
  getDoc: jest.fn(),
  setDoc: jest.fn(),
  addDoc: jest.fn(),
  updateDoc: jest.fn(),
  deleteDoc: jest.fn(),
  query: jest.fn(),
  where: jest.fn(),
  orderBy: jest.fn(),
  getDocs: jest.fn(),
  limit: jest.fn(),
  startAfter: jest.fn(),
  onSnapshot: jest.fn(),
  createUserWithEmailAndPassword: jest.fn(),
  signInWithEmailAndPassword: jest.fn(),
  signOut: jest.fn(),
  onAuthStateChanged: jest.fn(),
  registerVersion: jest.fn(),
};
